dist:
  name: jwtprocessor
  description: JWT singing processor for OpenTelemetry Collector
  output_path: ./dist

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.137.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.137.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.137.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.137.0

processors:
  - gomod: github.com/kawai/jwtprocessor v0.0.0
    path: ./


