openapi: 3.0.0
info:
  title: JWT Processor API
  version: 0.1.0
paths:
  /process:
    post:
      summary: Process JWT data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jwt:
                  type: string
                  description: JWT token to process
      responses:
        '200':
          description: JWT processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  claims:
                    type: object
        '400':
          description: Invalid JWT or request
